### ISSUE TITLE
./pcap-decrypt.py capture.pcapng.gz error

### ISSUE THREAD

**Issue by borewicz9** [ximihobi/mihome-binary-protocol#5]
```
Traceback (most recent call last):
  File "./pcap-decrypt.py", line 67, in <module>
    args.pcapfile, display_filter=("udp.port == 54321"))
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/file_capture.py", line 47, in __init__
    raise FileNotFoundError(str(self.input_filename))
FileNotFoundError: capture.pcapng.gz

```
Hello,
Need help with above error

**Comment by igoro00** [comment]
i think you should generate this using wireshark
Run wireshark for a while and save it to a file
